### ISSUE TITLE
High CPU consumption? 

### ISSUE THREAD

**Issue by liufuyang** [kubernetes-sigs/kubeadm-dind-cluster#177]
I simply used the wget script to start the cluster on mac.

Then I noticed that from the activity monitor or docker stats that the CPU usage seems pretty high for an pure empty cluster (with k8s inside of course), especially for the master node the cpu usage is 
jumping from 20% to 50%

![image](https://user-images.githubusercontent.com/161689/43251028-1cf94dd0-90bf-11e8-98c0-86069d51e86c.png)

Would like to ask that is this expected behavior and the same for everyone else?

---

My docker version
`Docker version 18.03.1-ce, build 9ee9f40`

Cluster started with command:
`./dind-cluster-v1.10.sh u`

**Comment by stratmm** [comment]
Hi @liufuyang,

I have been using 1.11.1-00 and 1.11.0-00.  I boot up a single master node to manually build an HA cluster and find the node is immediately using 50% of all four CPUs on the host.


Config File
```
apiVersion: kubeadm.k8s.io/v1alpha2
kind: MasterConfiguration
kubernetesVersion: v1.11.0
apiServerCertSANs:
- "10.131.0.9"
api:
    controlPlaneEndpoint: "10.131.0.9:6443"
etcd:
    external:
        endpoints:
        - http://10.131.0.12:2379
networking:
    # This CIDR is a calico default. Substitute or remove for your CNI provider.
    # podSubnet: "192.168.0.0/16"

```

Simply installed with 
```
apt-get -y install kubelet=1.11.1-00 kubeadm=1.11.1-00 kubectl=1.11.1-00
kubeadm config images pull
kubeadm init --config kubeadm-config.yaml
```

etcd is on a separate cluster behind a load balancer.
